--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.31.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/13/2018 12:26:41 PM
-- Server version: 5.5.5-10.1.32-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE sirclo_berat;

--
-- Definition for table berat
--
DROP TABLE IF EXISTS berat;
CREATE TABLE berat (
  id VARCHAR(36) NOT NULL,
  berat_min INT(4) DEFAULT NULL,
  berat_max INT(4) DEFAULT NULL,
  tanggal DATE DEFAULT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 5461
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table berat
--
INSERT INTO berat VALUES
('4986ce8a-ce90-11e8-9a41-88d7f6304099', 60, 68, '2018-10-12', 0),
('885e77fd-a2be-41f9-b17e-d3df1367b4ce', 63, 65, '2018-10-13', 0),
('bb549020-4f81-43e7-b903-0bb970851a9a', 65, 68, '2018-09-20', 0);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;