//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Berat.Web.Models
{
	/// <summary>
	/// Database       : sirclo_berat
	/// Data Source    : 127.0.0.1
	/// Server Version : 5.5.5-10.1.32-MariaDB
	/// </summary>
	public partial class SircloBeratDB : LinqToDB.Data.DataConnection
	{
		public ITable<Berat> Berats { get { return this.GetTable<Berat>(); } }

		public void InitMappingSchema()
		{
		}

		public SircloBeratDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public SircloBeratDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext();
	}

	[Table("berat")]
	public partial class Berat
	{
		[Column("id"),        PrimaryKey,  NotNull] public string    Id       { get; set; } // varchar(36)
		[Column("berat_min"),    Nullable         ] public int?      BeratMin { get; set; } // int(4)
		[Column("berat_max"),    Nullable         ] public int?      BeratMax { get; set; } // int(4)
		[Column("tanggal"),      Nullable         ] public DateTime? Tanggal  { get; set; } // date
		[Column("is_delete"),              NotNull] public bool      IsDelete { get; set; } // tinyint(1)
	}

	public static partial class TableExtensions
	{
		public static Berat Find(this ITable<Berat> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
